{
    "name" : "eMobility System",
    "version" : "1.0.1",
    "author" : "Affinity Digital Limited",
    "category" : "",
	"description": "This module is developed to manage the Mobility Centre process.",
    "depends" : [],
    "init_xml" : [],
    "demo_xml" : [],
    "update_xml" : ['view/users.xml',
                    'security/security.xml',
                    'view/email_templates.xml', 
                    'wizard/_wizard_reception.xml',
                    'view/cmc_administration.xml',
                    'view/cmc_person_view.xml',
                    'view/cmc_person_telephone_view.xml',
                    'view/cmc_person_address_view.xml',
                    'view/cmc_person_email_address_view.xml',
                    'report/_cmc_reports.xml',
                    'view/sxw_templates.xml',
                    'view/cmc_assessment_state_view.xml',
                    'view/cmc_assessment_outcome_view.xml',
                    'view/cmc_assessment_report_view.xml',
                    'view/cmc_assessment_price_view.xml',
                    'view/emobility_information_documents.xml',
                    'view/cmc_enquiry_view.xml',
                     'view/cmc_call_history_view.xml',
                    'view/cmc_search_view.xml',
                    'view/cmc_user_activity_view.xml',
                    'view/cmc_communication_view.xml',
                    'view/cmc_attachment_view.xml',
					'view/cmc_user_attachment_view.xml',
                    'view/cmc_equipment_attachment_view.xml',
                    'view/cmc_equipment_owner_history_view.xml',
                    'view/cmc_assessment_view.xml',
                    'view/doc_templates_view.xml',
                    'view/cmc_appointments.xml',
                    'view/cmc_equipment_view.xml',
                    'view/cmc_ordered_equipment_master_view.xml',
                    'view/cmc_equipment_supply_process_view.xml',
#                    'view/cmc_workshop_view.xml',
                    'view/cmc_adaptations_view.xml',
                    'view/cmc_assessment_communication_view.xml',
                    'view/sequences.xml',
                    'view/cmc_menu_wizard.xml',
                    'view/attachment.xml',
                    'security/ir.model.access.csv',
                    
                    
                    ],
    "installable": True,
    "active": False
}
